### ISSUE TITLE
✨ Support template-base changelog maintenance 

### ISSUE THREAD

**Issue by ckunki** [exasol/python-toolbox#106]
# Summary

The current ticket request to enhance PTB in order to support users to maintain the changelog or their application projects.

# Details

Proposed work-flow for starting to work on a new version of the current application 

* user assigns new version in `pyproject.toml` and calls 
   * either `poetry run nox -s fix`
  * or `poetry run version-check <path/version.py> --fix`
* PTB 
  * updates file `doc/changes/changelog.md`
  * creates file `doc/changes/unreleased.md` with content from template (see below) 

Proposed work-flow for finishing and releasing a new version of the current application 

* PTB 
  * validates content of file `doc/changes/unreleased.md` (specification: TBD) and reports potential findings 
  * renames file `doc/changes/unreleased.md` to  file `doc/changes/changes_<version>.md` using the version from  file `pyproject.toml`.
  * sets release date (if possible / appropriate) 
    * maybe this needs to be done in a later step?
  * updates file `doc/changes/changelog.md`

Proposed template, see https://github.com/exasol/notebook-connector/blob/main/doc/changes/changes_0.2.2.md

```
# <project-name from README.md> <version>, released t.b.d

Code name:

## Summary

<please enter summary here>

<!-- Sections: Changes, Features, Bugfixes, Refactorings, Documentation, Security -->
## Changes

* ISSUE_NUMBER: description
``` 
 
## Background & Context

Automation, convenience, reduce manual work, increase quality, unify workflows, provide guidance for developers not familiar with processes and tools in Exasol Product Integration Team.

## Examples

Sample repo already using the PTB: https://github.com/exasol/notebook-connector 

## References

Compare workflows with [project-keeper](https://github.com/exasol/project-keeper) and [release-droid](https://github.com/exasol/release-droid).

**Comment by Nicoretti** [comment]
Closing this issue, due to the fact that most of the mentioned functionality is provided by the newly added `nox -s prepare-release -- <version>` tasks.
