### ISSUE TITLE
📚 Add documentation how to prepare and create a new release using the PTB

### ISSUE THREAD

**Issue by ckunki** [exasol/python-toolbox#198]
# Summary
Currently, [PTB's documentation](https://exasol.github.io/python-toolbox/user_guide/user_guide.html) does not describe how to prepare or create a new release.

# Details
Compare [Developer Guide of SAPIPY](https://github.com/exasol/saas-api-python/blob/main/doc/developer_guide/developer_guide.md#creating-a-release).

**Comment by Nicoretti** [comment]
See https://exasol.github.io/python-toolbox/developer_guide/development.html#creating-a-release
