### ISSUE TITLE
🐞 Coverage report on new empty project fails hiding stderr of subproccess

### ISSUE THREAD

**Issue by ckunki** [exasol/python-toolbox#222]
File [exasol/toolbox/metrics.py](https://github.com/exasol/python-toolbox/blob/main/exasol/toolbox/metrics.py#L82) in method `total_coverage()` calls `subprocess.run()`:

```
        run(
            ["coverage", "json", f"--data-file={file}", "-o", f"{report}"],
            capture_output=True,
            check=True,
        )
```

A [sample CI build](https://github.com/exasol/text-ai-extension/actions/runs/9941329347/job/27460167483?pr=3#step:6:29) displays the following error message. 
```
subprocess.CalledProcessError: Command '['coverage', 'json', 
'--data-file=.coverage', 
'-o', '/tmp/tmpd9c4d11b/coverage.json']' 
returned non-zero exit status 2.
nox > Session report failed.
```

The current ticket proposes to 
* surround the call by try/catch and 
* When catching `CalledProcessError` then report `stdout` and `stderr` of the subprocess
* re-raise the exception then again

Additionally 
* The template for file [test/unit/unit_smoke_test.py](https://github.com/exasol/python-toolbox/blob/main/project-template/%7B%7Bcookiecutter.repo_name%7D%7D/test/unit/unit_smoke_test.py) uses `import exasol.text_ai_extension` but 
* file [exasol/text_ai_extension/__init__.py](https://github.com/exasol/python-toolbox/blob/main/project-template/%7B%7Bcookiecutter.repo_name%7D%7D/exasol/%7B%7Bcookiecutter.package_name%7D%7D/__init__.py)  still contains no actual line of code 
* which in result still makes coverage fail when in file `pyproject.toml` using threshold `fail_under = 15`

I was able to make coverage report terminate successfully by 
* adding a function to `__init__.py`, e.g. (see below) 
* importing the function into the test and verifying its value in the test:

File `__init__.py`:
```python
def sample_function():
    return True
```

file `test/unit/unit_smoke_test.py`:
```python
import {{ cookiecutter.import_package }}

def test_unit_smoke_test():
    assert {{cookiecutter.package_name}}.sample_function() 
```

**Comment by Nicoretti** [comment]
Importing the pre-existing `version` constant(s) would likely yield a more sensible test. 

For example, a unit test that verifies the version in `version.py` is in sync with the version in `pyproject.toml` could simultaneously address two issues:

1. The explicit version check workflow step could be eliminated.
2. Some code from the module in question would be tested.
