### ISSUE TITLE
✨ Handle multiple runs of linter and coverage in metric report

### ISSUE THREAD

**Issue by ckunki** [exasol/python-toolbox#223]
This ticket needs to be fixed before 2024 Nov 30, see https://github.com/actions/upload-artifact.

Currently, only a single file `.lint.txt` or `.coverage`  is evaluated in `metrics.py`.

This also leads to problems with github `actions/upload-artifact`  and `actions/download-artifact`  which have slightly different semantics in `@v4` vs. `@v3`. Additionally, actions upload- and download- must be using the same version.

The current implementation additionally is inconsistent, as the single file may be randomly selected. 

The current ticket proposes to 
* to ensure unique filenames by adding a prefix for the matrix build coordinate, e.g. python version 
* enhance the report to 
  * Merge the coverage of all runs for all matrix build coordinates
  * Create an aggregated version of the linter results, e.g. average, max, or min score.
* Merging is also required when separating different classes of tests, e.g. fast vs. slow tests, see https://github.com/exasol/saas-api-python/issues/53

**Comment by tkilias** [comment]
In a first version, the linter reports could be merged by having a section for each matrix build coordinates

**Comment by Nicoretti** [comment]
This issue is related to: https://github.com/exasol/python-toolbox/issues/223

**Comment by Nicoretti** [comment]
Addressed by:

* #181
* #246

and their respective PR's
