### ISSUE TITLE
✨ Add nox task to verify dependency declarations

### ISSUE THREAD

**Issue by ckunki** [exasol/python-toolbox#233]
# Summary
`pyproject.toml` support different alternatives for declaring dependencies to other python packages:
* reference to a release published on `pypi`
* reference to a path in the local file system
* reference to a GitHub repository, optionally including a branch or commit SHA1

# Details

The PTB should be enhanced 
* to detect other references other than those to releases published on `pypi` 
* avoid merging to the main branch

## Background & Context

The Exasol Integration Team decided to only use references to releases published on `pypi`.
Other references turned out to cause inconsistencies in dependencies and a lot of trouble.

## Tasks 

* [ ] add nox task 
* [ ] enhance templates for GitHub workflows

**Comment by Jannis-Mittenzwei** [comment]
waiting for review by @Nicoretti

**Comment by ckunki** [comment]
Could @Nicoretti please review ?
