### ISSUE TITLE
🐞 Version check issues

### ISSUE THREAD

**Issue by Nicoretti** [exasol/python-toolbox#29]
# Summary
Currently the version check(s) have various small errors/bugs.

* Invalid parameters are passed when called via `nox`
* On some platforms (e.g. windows color needs to be turned of explicitly)

### Parameter Issue
version-check fails 
```
$ version-check -f github_issue_adapter/version.py
Error while executing program, details: Couldn't find version within module
```

File `exasol/toolbox/nox/tasks.py`
Remove `--fix`
```
command = ["poetry", "run", "version-check"]
```

### Color Escape Sequences Issue
File `exasol/toolbox/pre_commit_hooks/package_version.py`
Add option `--no-ansi`
```
result = subprocess.run([poetry, "version", '--no-ansi'], capture_output=True)
```

**Comment by ckunki** [comment]
Hello @MarleneKress79789 I tested both changes successfully.

#### Test strategy change I (remove option `--fix`):
* I checked out the branch of the PTB corresponding to the current ticket
* in the working copy of my repo I called `poetry add ..\python-toolbox`
* I called `poetry run version-check github_issue_adapter/version.py` without `-f` and did not observe an error
* I called `poetry run version-check -f github_issue_adapter/version.py` and did not observe an error, either

#### Test strategy change II (add optino `--no-ansi`):
* I called `poetry run python -m exasol.toolbox.pre_commit_hooks.package_version github_issue_adapter\version.py
` and did not observe any error, anymore.

Strangely removing the option `--no-ansi` in my virtual poetry env did not show any error, either. But the change probably still improves the stability and does not cause additional problems on windows, either.

So from my perspective I can safely approve the changes based on my review results.
