### ISSUE TITLE
✨ Support updating file version.py based on version information in file pyproject.toml

### ISSUE THREAD

**Issue by ckunki** [exasol/python-toolbox#51]
# Summary

Currently the developer will set the version number with `poetry version <version>`.
Additionally there is a file `version.py` creating the risk for inconsistencies.
File `version.py` also contains a comment that the file is created automatically and should not be edited manually. 
But there seems to be no automation, yet.

So the current ticket therefore requests to create and describe an automation.
Options 
- pre commit hook
- nox task

**Comment by MarleneKress79789** [comment]
The existing command "poetry run version-check exasol/toolbox/version.py --fix" updates version.py to match pyproject.toml which is used in "exasol/toolbox/pre_commit_hooks/package_version.py" as far as i can see.

**Comment by ckunki** [comment]
I get 
> Error while executing program, details: [Errno 2] No such file or directory: 'exasol/toolbox/version.py'

**Comment by ckunki** [comment]
OK, as I am not developing the toolbox itself, my file was in a different location.
I could successfully update the version with 
```
cd github_issue_adapter
poetry run version-check version.py --fix 
```
