### ISSUE TITLE
✨ Enable caching of python packages in GitHub actions

### ISSUE THREAD

**Issue by kaklakariada** [exasol/python-toolbox#52]
# Summary
Enable caching of python packages in GitHub actions

# Details
Caching python packages installed via poetry will save a lot of time and energy.

## References
See documentation of setup-python action: https://github.com/actions/setup-python#caching-packages-dependencies

* https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages
* https://github.com/exasol/exasol-python-test-framework/pull/57/files#r1607680555
```[tasklist]
### Tasks
- [ ] Enable caching in toolbox
- [ ] Use caching in all python projects
```

**Comment by tomuben** [comment]
Need to use `pipx` to install poetry instead of the `abatilo` GH action, check:
https://github.com/exasol/exasol-python-test-framework/pull/57/commits/1eb70dc010738b3c8e339db2c9e9679ea1c11a04
But the setup seems to work, I tested it with pipx and it installs the correct environment.
